name: Build Chromium

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      WINDOWS_SDK_VERSION: "10.0.19041.0" # see build/toolchain/win/setup_toolchain.py
      WINDOWS_TOOLCHAIN_HASH: "fdfc420dcd"

    steps:
      - uses: actions/checkout@v2

      - name: 0.  [All] Print environment
        shell: bash
        run: |
          echo "WINDOWS_SDK_VERSION:    ${{ env.WINDOWS_SDK_VERSION }}"
          echo "WINDOWS_TOOLCHAIN_HASH: ${{ env.WINDOWS_TOOLCHAIN_HASH }}"

# Debian Dependencies
# https://wiki.qt.io/Building_Qt_5_from_Git

      - name: 1.  [Linux] Add Build Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get build-dep qt5-default
          sudo apt-get install '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev
          sudo apt-get install libssl-dev libxcursor-dev libxcomposite-dev libxdamage-dev libxrandr-dev libdbus-1-dev libfontconfig1-dev libcap-dev libxtst-dev libpulse-dev libudev-dev libpci-dev libnss3-dev libasound2-dev libxss-dev libegl1-mesa-dev gperf bison
          sudo apt-get install libasound2-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev

      - name: 2.  [All] Run Script
        run: yes | bash update.sh -e

#      - name: 3.  [Windows] Make SDK toolchain zip
#        if: matrix.os == 'windows-latest' && steps.github-cache.outputs.cache-hit != 'true'
#        shell: bash
#        working-directory: ${{ env.DEPOT_TOOLS_DIR }}/win_toolchain
#        run: |
#          sed -i "/if len(matches)/s/^/#/g" package_from_installed.py #comment
#          sed -i "/  raise Exception('%s h/s/^/#/g" package_from_installed.py #comment
#          python package_from_installed.py 2019 -w ${{ env.WINDOWS_SDK_VERSION }}
#          cp *.zip ../../github_cache/
