name: Build Chromium

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      QT_VERSION: "5.15.2"
      QT_PACKAGE_NAME: "qt-everywhere-src-$QT_VERSION"
      WORK_DIR: "$HOME/Code"
      DEPOT_TOOLS_DIR: "$HOME/Code/depot_tools"
      QT_DIR: "$HOME/Code/qt-everywhere-src-$QT_VERSION"
      QT_BUILD_DIR: "$HOME/Code/qt5-build"
      WEB_ENGINE_DIR: "$HOME/Code/qt-everywhere-src-$QT_VERSION/qtwebengine"
      THIRD_PARTY_DIR: "$HOME/Code/qt-everywhere-src-$QT_VERSION/qtwebengine/src/3rdparty"
      CHROMIUM_DIR: "$HOME/Code/qt-everywhere-src-$QT_VERSION/qtwebengine/src/3rdparty/chromium"

    steps:
      - uses: actions/checkout@v2

      - name: Print environment
        shell: bash
        run: |
          echo "QT_VERSION:           ${{ env.QT_VERSION }}"
          echo "QT_PACKAGE_NAME :     ${{ env.QT_PACKAGE_NAME }}"
          echo "WORK_DIR:             ${{ env.WORK_DIR }}"
          echo "DEPOT_TOOLS_DIR:      ${{ env.DEPOT_TOOLS_DIR }}"
          echo "QT_DIR:               ${{ env.QT_DIR }}"
          echo "QT_BUILD_DIR:         ${{ env.QT_BUILD_DIR }}"
          echo "WEB_ENGINE_DIR:       ${{ env.WEB_ENGINE_DIR }}"
          echo "WEB_ENGINE_DIR:       ${{ env.THIRD_PARTY_DIR }}"
          echo "CHROMIUM_DIR:         ${{ env.CHROMIUM_DIR }}"

      - name: 1.  Make work directory
        shell: bash
        working-directory: ${{ env.HOME }}
        run: mkdir -p ${{ env.WORK_DIR }}

      - name: 2.  Get Depot Tools
        shell: bash
        working-directory: ${{ env.WORK_DIR }}
        run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git

